cluster:
  name: cluster11
overrideVar2: overrideVar2Env
test: 123
replicas: 4444
overrideFromDiffEnv: overrideFromDiffEnvFromEnv
overrideTest: ovverrideTestFromEnv
overrideVar3: overrideVar3Env
anotherPorts:
  http: 6666
anything: test
envTag: eu1
testPorts:
  http: 5555
manifest_path: oath2
common:
  envTag: eu1
  namespace: alexc-argocd
overrideSvcSecretVar: secret
portFromStep:
  http: 33
serviceTag: multisource
containerPorts:
  http: 81
deployment:
  envTag: eu1
  namespace: alexc-argocd
