apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  namespace: mirko-cbp-test-ha
  name: nginx-applicationset
spec:
  generators:
    - git:
        repoURL: https://github.com/mteodor/argocd-example-apps
        revision: HEAD
        files:
          - path: "applicationset/performance/**/config.json"
  template:
    metadata:
      name: '{{cluster.namespace}}-nginx'
    spec:
      project: f6bd2309
      source:
        repoURL: https://github.com/mteodor/argocd-example-apps
        targetRevision:  master
        path: nginx
        helm:
          valueFiles:
            - '{{path}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{cluster.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true








