apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multisource-mteodor-appset
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/mteodor/argocd-example-apps
        revision: syncstep-multisource
        files:
          - path: helm2/app1/*/*/values.yaml
  template:
    metadata:
      name: {{.path.basename}}}
    spec:
      project: 8e143fca
      sources:
        - repoURL: https://github.com/mteodor/argocd-example-apps
          targetRevision: syncstep-multisource
          path: helm-nginx
        - repoURL: https://charts.bitnami.com/bitnami
          targetRevision: 18.1.2
          chart: nginx
      destination:
        server: https://kubernetes.default.svc
        namespace: {{.path.basename}}
      syncPolicy:
        automated: {}
